### ISSUE TITLE
S1.6.2 It isn't possible to filter books by name and category

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#93] opened 2020-12-08 10:52 UTC
Build version:
1.6.0

Steps to reproduce:

   1. Create a Book. Use any name and category (e.g.: name- Test2 , category- Fantasy);
   2. Open "Book search" page;
   3. Choose category of the book from step 1 in the "Category " drop-down list;
   4. Type a title of the book from step 1  in the "Book name " field;
   5. Tap on the button "Filter".

Actual result: The book from step 1 isn't showing.
Expected result: The book from step 1 is showing.

**Comment by ordeh** [comment] 2020-12-08 13:42
Duplicate of https://github.com/tasks-delivery/book-management/issues/92

**Closed as completed** 2020-12-08 13:43 UTC
Labels: bug, duplicate, front-end, p1
